flavor_text = {'rain': [
        'Go grab your fucking umbrella.',
        'PS, you are going to get wet today.',
        'Fuck you, water.',
        'Precipi-fucking-tation.',
        'Mutha fucking rain.',
        'The shitty part of the water cycle',
        'Because you just washed your car, sucka.',
        'It\'s good for plants, sucks for you.',
        'Stop bitching, it\' the same stuff they make beer out of.',
    ],
    'sunny': [
        'What are you doing inside? Get the fuck outside.',
        'Go on a hike, or something. Shit.',
        'You have 5 seconds to go grab a cold beer.',
        'It\'s fucking sunny!',
        'Get yer fucking sunglasses, asshole.',
        'If you have an office job, I am sorry you have to see the world from behind a window.',
        'Time for some mutha fucking Sunny D!',
        'It\'s all rainbows and butterflies and muthafucking pink bunnies outside.',
        'Do something with your life.',
        'Ride a bike for fuck\'s sake!',
        'Call in sick to work today',


    ],
    'snow': [
        'Where the fuck am I, the North Pole?',
        'Don\'t eat the yellow snow today',
        'It\'s fucking snowing outside!',
        'Time to shovel some snow today, asshole',
        'Go make a fucking snowman',
        'Take a snowball to the face',
        'There\'s snow! Pretend like you can\'t drive and don\'t go to work',
        'It\'s cool until you live in it',
    ],
    'cloudy': [
        'Where the fuck did the sun go?',
        'DAMN YOU, CLOUDS!',
        'Where the hell am I supposed to get my fucking Vitamin D now?',
        'Today is UUUUUUUGLY',
        'Fucking clouds. I hate them.',
        'The sun says "I\'ll be back." You know, like in the movie Terminator?',
        'Nothing special about today. Just another fucking boring, cloudy day',
        'Couds: HOW DO THEY EVEN WORK',
    ],
    'light-rain': [
        'Damnit, it might rain today',
        'Grab your fucking raincoat. Just in case.',
        'Your fortune says "You may get wet today"',
        'Roll the fucking dice. Chance of rain',
        'Sure, you can still use it as an excuse to stay inside. You lazy piece of shit',
        'Just pissin a little bit',
        'Just enough to fuck up your smartphone',
    ],
    'thunder': [
        'Maybe today you will get a lightning scar like Harry Potter',
        'Caution: There\'s a mutha fucking storm today',
        'May be we should just call it a day',
        'ZEUS IS NOT AMUSED!',
        'Hide yo kids, hide yo wife',

    ]
    }
